# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6ad2f9ed826af66a6fce134a64778a053d1c35d3971ff54251b32a197f93e898411b2d342715cd78267cdabc0d1d5596d22599c2a11e452dd703777f748c7db

test:
  secret_key_base: 19df24ca4bfba188bb1d9a58f146cfd8047fd816a4a3c990303a49be006d8f9f8acadfc534e13513552a265ee8dde6cb10c94813a50d2af949297c67c13d3da4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
